spring:
  profiles:
    default: dev

---
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 9093

spring:
  config:
    activate:
      on-profile: local
#H2
  h2:
    console:
      enabled: true
      path: /h2-console
#Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: SA
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
